In [1]:
# Get API_KEY from https://covidactnow.org/data-api
import pandas as pd
import config
import requests
from config import API_KEY

In [2]:
# Time series for all states
covid_df = pd.read_csv(f'https://api.covidactnow.org/v2/states.timeseries.csv?apiKey={API_KEY}')

In [3]:
covid_df.head(1000)

,date,country,state,county,fips,lat,long,locationId,actuals.cases,actuals.deaths,...,riskLevels.overall,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,actuals.newDeaths,actuals.vaccinesAdministered,riskLevels.caseDensity,cdcTransmissionLevel,actuals.vaccinationsAdditionalDose,metrics.vaccinationsAdditionalDoseRatio,metrics.weeklyNewCasesPer100k
0,2020-03-01,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0.0
1,2020-03-02,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0.0
2,2020-03-03,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0.0
3,2020-03-04,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0.0
4,2020-03-05,US,AK,NaN,2,NaN,NaN,iso1:us#iso2:us-ak,NaN,NaN,...,0,NaN,NaN,NaN,NaN,0,0,NaN,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2020-10-27,US,AL,NaN,1,NaN,NaN,iso1:us#iso2:us-al,183872.0,2892.0,...,3,NaN,NaN,26.0,NaN,3,3,NaN,NaN,191.7
996,2020-10-28,US,AL,NaN,1,NaN,NaN,iso1:us#iso2:us-al,185141.0,2911.0,...,3,NaN,NaN,19.0,NaN,3,3,NaN,NaN,194.6
997,2020-10-29,US,AL,NaN,1,NaN,NaN,iso1:us#iso2:us-al,186584.0,2914.0,...,3,NaN,NaN,3.0,NaN,3,3,NaN,NaN,195.9
998,2020-10-30,US,AL,NaN,1,NaN,NaN,iso1:us#iso2:us-al,187931.0,2932.0,...,3,NaN,NaN,18.0,NaN,3,3,NaN,NaN,195.4
999,2020-10-31,US,AL,NaN,1,NaN,NaN,iso1:us#iso2:us-al,189720.0,2967.0,...,3,NaN,NaN,35.0,NaN,3,3,NaN,NaN,183.7

In [4]:
len(covid_df)

40142

In [5]:
covid_df.columns

Index(['date', 'country', 'state', 'county', 'fips', 'lat', 'long',
       'locationId', 'actuals.cases', 'actuals.deaths',
       'actuals.positiveTests', 'actuals.negativeTests',
       'actuals.contactTracers', 'actuals.hospitalBeds.capacity',
       'actuals.hospitalBeds.currentUsageTotal',
       'actuals.hospitalBeds.currentUsageCovid', 'unused1',
       'actuals.icuBeds.capacity', 'actuals.icuBeds.currentUsageTotal',
       'actuals.icuBeds.currentUsageCovid', 'unused2', 'actuals.newCases',
       'actuals.vaccinesDistributed', 'actuals.vaccinationsInitiated',
       'actuals.vaccinationsCompleted', 'metrics.testPositivityRatio',
       'metrics.testPositivityRatioDetails', 'metrics.caseDensity',
       'metrics.contactTracerCapacityRatio', 'metrics.infectionRate',
       'metrics.infectionRateCI90', 'unused3', 'unused4',
       'metrics.icuCapacityRatio', 'riskLevels.overall',
       'metrics.vaccinationsInitiatedRatio',
       'metrics.vaccinationsCompletedRatio', 'actuals.newDeaths',
       'actuals.vaccinesAdministered', 'riskLevels.caseDensity',
       'cdcTransmissionLevel', 'actuals.vaccinationsAdditionalDose',
       'metrics.vaccinationsAdditionalDoseRatio',
       'metrics.weeklyNewCasesPer100k'],
      dtype='object')

In [6]:
#Drop columns that are irrelevant
covid_df_clean1 = covid_df.drop(columns=['metrics.caseDensity','metrics.contactTracerCapacityRatio','metrics.infectionRateCI90','riskLevels.overall','metrics.vaccinationsInitiatedRatio','actuals.vaccinesAdministered','riskLevels.caseDensity','metrics.testPositivityRatioDetails','metrics.testPositivityRatio','actuals.vaccinationsCompleted','actuals.cases','actuals.deaths', 'actuals.positiveTests','actuals.negativeTests','unused2','actuals.icuBeds.currentUsageCovid','country','county','fips','lat','long','actuals.contactTracers', 'actuals.hospitalBeds.capacity','actuals.hospitalBeds.currentUsageTotal','unused1','actuals.icuBeds.capacity','actuals.icuBeds.currentUsageTotal','unused3', 'unused4','metrics.icuCapacityRatio','locationId','actuals.vaccinesDistributed','actuals.vaccinationsInitiated', 'cdcTransmissionLevel','actuals.vaccinationsAdditionalDose', 'metrics.vaccinationsAdditionalDoseRatio' ])

In [7]:
covid_df_clean1.columns

Index(['date', 'state', 'actuals.hospitalBeds.currentUsageCovid',
       'actuals.newCases', 'metrics.infectionRate',
       'metrics.vaccinationsCompletedRatio', 'actuals.newDeaths',
       'metrics.weeklyNewCasesPer100k'],
      dtype='object')

In [8]:
#drop null 
covid_df_clean1.dropna()

,date,state,actuals.hospitalBeds.currentUsageCovid,actuals.newCases,metrics.infectionRate,metrics.vaccinationsCompletedRatio,actuals.newDeaths,metrics.weeklyNewCasesPer100k
288,2020-12-14,AK,133.0,429.0,0.82,0.000,0.0,548.6
289,2020-12-15,AK,135.0,282.0,0.81,0.000,3.0,508.8
290,2020-12-16,AK,142.0,611.0,0.80,0.000,2.0,512.1
291,2020-12-17,AK,133.0,383.0,0.79,0.000,2.0,477.5
292,2020-12-18,AK,135.0,493.0,0.79,0.000,0.0,459.2
...,...,...,...,...,...,...,...,...
40137,2022-03-21,WY,16.0,0.0,0.80,0.509,0.0,29.5
40138,2022-03-22,WY,12.0,81.0,0.81,0.509,14.0,29.9
40139,2022-03-23,WY,12.0,0.0,0.83,0.510,0.0,28.5
40140,2022-03-24,WY,10.0,0.0,0.84,0.510,0.0,27.1
40141,2022-03-25,WY,10.0,68.0,0.86,0.510,0.0,25.7

In [9]:
covid_df_clean1.head()

,date,state,actuals.hospitalBeds.currentUsageCovid,actuals.newCases,metrics.infectionRate,metrics.vaccinationsCompletedRatio,actuals.newDeaths,metrics.weeklyNewCasesPer100k
0,2020-03-01,AK,NaN,NaN,NaN,NaN,NaN,0.0
1,2020-03-02,AK,NaN,NaN,NaN,NaN,NaN,0.0
2,2020-03-03,AK,NaN,NaN,NaN,NaN,NaN,0.0
3,2020-03-04,AK,NaN,NaN,NaN,NaN,NaN,0.0
4,2020-03-05,AK,NaN,NaN,NaN,NaN,NaN,0.0

In [10]:
#filter the dataframe
covid_df_filtered = covid_df_clean1.loc[(covid_df_clean1['date'] >= '2021-03-01') & (covid_df_clean1['date'] < '2022-02-28')]
covid_df_filtered.head(10)

,date,state,actuals.hospitalBeds.currentUsageCovid,actuals.newCases,metrics.infectionRate,metrics.vaccinationsCompletedRatio,actuals.newDeaths,metrics.weeklyNewCasesPer100k
365,2021-03-01,AK,25.0,383.0,0.99,0.000,10.0,124.8
366,2021-03-02,AK,27.0,154.0,0.99,0.000,1.0,138.3
367,2021-03-03,AK,34.0,191.0,0.99,0.000,1.0,140.0
368,2021-03-04,AK,32.0,148.0,0.99,0.000,0.0,134.9
369,2021-03-05,AK,36.0,148.0,0.99,0.146,1.0,140.0
370,2021-03-06,AK,39.0,0.0,0.99,0.150,0.0,138.0
371,2021-03-07,AK,37.0,0.0,0.99,0.156,0.0,136.1
372,2021-03-08,AK,35.0,340.0,0.99,0.158,0.0,134.1
373,2021-03-09,AK,34.0,89.0,0.99,0.160,0.0,125.2
374,2021-03-10,AK,40.0,152.0,0.99,0.163,0.0,119.9

In [11]:
covid_df_filtered.to_csv('Resources\COVID_Filtered.csv', index = False)